### ISSUE TITLE
New Data Model - Sprint Plan

### ISSUE THREAD

**Issue by jalavik** [inveniosoftware/jsonalchemy#21]
This is the current sprint plan of the implementation of the new jsonalchemy model.

We are going to attack the internal and public API using TDD. The first round of major features to implement in this sprint will be:
- [ ] class based internal API (ElasticSearch DSL)
- [ ] public API as "JSON" style (`__get(item|attr)__`, `__set(item|attr)__`) (warlock style)
- [ ] clean exception handling (avoid using lambdas - no hidden errors)
- [ ] validation "always" on set (strict vs. relaxed)
- [ ] model factory (inheritance, composability)
- [ ] Pythonic types (date, time, utc)
- [ ] "read-only", calculated (extendable with signals upon set_attr? relation models?),
- [ ] Multiple schema support (e.g. support migrations)

At the same time the process will be as follows:
- Writing the tests as we want to use the APIs (following TDD approach)
- "99% coverage"
- Sprints structured in pairs and groups (everyone staying close together for frequent discussion & review)
- New sprint branch as `pu` branch on this repo.
- "Final" state of branch squashed and committed as @invenio-developers with co-authorships

**Comment by lnielsen** [comment]
:+1: :-)

**Comment by jirikuncar** [comment]
> - [ ] Pythonic types (date, time, utc)

@jacquerie can you have a look at it?

**Comment by jacquerie** [comment]
@jirikuncar Yup, was already looking into it.

**Comment by jirikuncar** [comment]
We are using JSON schemas directly instead.
