### ISSUE TITLE
RFC: External enum

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/jsonalchemy#33]
It should be possible to express the fact that a given attribute has a value within a list of values computed at runtime (e.g. by query a DB table).

For that we would basically need to be able to provide to the model a function that evaluates to True, accordingly, based on the given value. 

``` json
{"recid": 123,
 "authors": [{"name": "foo",
                    "affiliation": "Bar University"}]}
```

Where the `Bar University` would be checked by a `is_valid_institution("Bar University") function.

**Comment by MSusik** [comment]
:+1: proved to be useful for some use cases (for example authors records).

**Comment by MSusik** [comment]
Will be implemented not as _external enum_ but as additional external validation.

Inside the validation function, should the developer have the whole record available or just the current field?

**Comment by jacquerie** [comment]
In this case, I'd go with only the current field. The API should suggest that this check will be done locally, and not allow arbitrary checks in unrelated fields.

**Comment by MSusik** [comment]
However, it is a different behaviour than in `calculated` fields, where currently (branch new_approach in my repo) we will be passing the whole record.

What would be nice, is:
- passing only current field in the external validation
- passing both current field and the whole record to the calculated fields. It would make the functions reusable if they only use the current field for the computations.

**Comment by MSusik** [comment]
One possible solution is implemented in: https://github.com/MSusik/jsonalchemy/commit/a8f3e1f674c94b5933908b8ff226db196cb6f5ec

**Comment by jirikuncar** [comment]
We are going to use native JSON schema enums.
