### ISSUE TITLE
RFC: Calculating derived fields

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/jsonalchemy#34]
It should be possible to have a given record instance to be in two states. One that is _raw_, i.e. it represents exactly the parsed JSON values, and one where it is _completed_ (or whatever naming we find), so that some of its attributes are populated at runtime by provided functions. These function will need to receive a context which might be necessary e.g. to query a DB. 

E.g.

``` json
{"recid": 123,
 "citations": null,
}
```

could be a `raw` record.

Then this could be populated into:

``` json
{"recid": 123,
 "citations: [234,456,787]}
```

where a given function:

``` python
def get_citations(object):
    return _get_citations(object["recid"])
```

**Comment by MSusik** [comment]
What is the desired API?

``` python
>>> data = JSONObject({"recid": 123}, schema=schema_with_citations)
>>> data["citations"]
None

>>> data.derive() # Or whichever name you like
>>> data["citations"]
[234,456,787]

```

or

``` python
>>> data = JSONObject({"recid": 123}, schema=schema_with_citations, raw=True)
>>> data["citations"]
None
>>> data.derive() # Or whichever name you like
>>> data["citations"]
[234,456,787]
>>> data = JSONObject({"recid": 123}, schema=schema_with_citations)
>>> data["citations"]
[234,456,787]
```

or

``` python
>>> data = JSONObject({"recid": 123}, schema=schema_with_citations)
>>> data.raw["citations"] #Maybe data["citations"].raw ?
None
>>> data["citations"]
[234,456,787]
```

?

EDIT: @jacquerie : Indeed, it made no sense. Fixed now.

**Comment by jacquerie** [comment]
I'm confused. what is `["citations"]` doing there? I'd expect that would be what's returned when querying for `data`. I'm rewriting the third (which is the one I like the most):

``` shell
>>> data = JSONObject({"recid": 123}, schema=schema_with_citations)
>>> data.raw
{"recid": 123,
 "citations": null,
}

>>> data["citations"]
[234,456,787]

>>> data
{"recid": 123,
 "citations: [234,456,787]
}

>>> data.raw
{"recid": 123,
 "citations": null,
}
```

**Comment by jmartinm** [comment]
That looks good @jacquerie

If you wanted to get all the calculated fields maybe you can complete the example with something like @MSusik proposed

``` python
>>> data.derive() 
```

Or for the naming, maybe 

``` python
>>> data.dumps() 
```

**Comment by MSusik** [comment]
What about `data["citations"].raw` vs `data.raw["citations"]`?

**Comment by MSusik** [comment]
Question nr.2:

Do we want to implement as well `data.dump()` (not dumps) method?

**Comment by jacquerie** [comment]
1. I'd say `data["citations"].raw`.
2. @jirikuncar was also asking that in https://github.com/inveniosoftware/jsonalchemy/pull/31#issuecomment-97764452. I'd say that `json.dumps` is enough (and is open for extension: `xml.dumps` and similar).

**Comment by lnielsen** [comment]
> What about data["citations"].raw vs data.raw["citations"]?

Stupid question perhaps but with `data["citations"].raw` can't you get into situation where you masquerade an existing attribute?

**Comment by jirikuncar** [comment]
Calculation should be done on before insert/update actions.
