### ISSUE TITLE
RFC: invert the semantics of `with` blocks

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/jsonalchemy#35]
In https://github.com/inveniosoftware/jsonalchemy/pull/29#issuecomment-95615489 the following API is proposed to "suspend validation":

``` python
data = JSONDict({'a': []})
with data.transaction() as d:  # validation is turned off until __exit__
    for i in range(10000):
        d['a'].append(i)
```

I'm proposing instead to invert the semantics, and use `with` blocks for validation. Any mutation outside of a `with` block will just succed, and not fire the validation. The recommended way of having validation is using a `with` block, which will validate the entire record.

A problem with the current approach is that a few JSON schema features require us to check the parent on modification. For example, given the following JSON schema

``` JSON
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "foo": { "type": "integer" }
        }
    },
    "uniqueItems": true
}
```

and the following data

``` python
data = JSONList([{"foo": 1}, {"foo": 2 }], schema=schema)
```

then this mutation should fail

``` python
data[0]['foo'] = 2
```

since it is violating the parent's `uniqueItems` constraint (credit for this observation goes to @MSusik).

Using this proposal's API we'd have:

``` python
with data.validate() as d:
    d[0]['foo'] = 2  # Will fail on __exit__, when the validation is run on d
```

while instead the mutation

``` python
data[0]['foo'] = 2
```

will skip the validation (since this might be the programmer's intent).

CC: @jalavik @jirikuncar

**Comment by jirikuncar** [comment]
sounds good :+1:

**Comment by MSusik** [comment]
If I understood correctly:
1).Using the `with` statement validation will be run only on exit (so, the behaviour won't change)
2).Not using validation, there will be no validation at all
3).Developer will have an easy access to `validate` method all the time.

Implementing such solution, we can also think of implementing proper `JSONString`s, `JSONInt`s, etc.

**Comment by lnielsen** [comment]
:+1:

**Comment by MSusik** [comment]
The code is available here:
https://github.com/inveniosoftware/jsonalchemy/pull/30
