### ISSUE TITLE
RFC: JSON types

### ISSUE THREAD

**Issue by MSusik** [inveniosoftware/jsonalchemy#36]
With the inverted semantic for `with` statement, implementing new objects such as `JSONString`, `JSONInt`, etc. won't require writing huge amonts of code.

By doing so, we can in future fully support v4 specification of `JSONSchema`.

Can we have this feature? I'd like to implement it.

**Comment by jacquerie** [comment]
I'm in favor, so that [Jimmy](http://blog.codinghorror.com/new-programming-jargon/) won't be confused by the lack of validation on naked formatted strings.

**Comment by jirikuncar** [comment]
We have moved towards native JSON schemas.
