### ISSUE TITLE
RFC: use of JSONPath

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/jsonalchemy#39]
The previous JSONAlchemy used the syntax `foo['bar.baz.quux']` to shorten `foo['bar']['baz']['quux']`, for example here: https://github.com/inveniosoftware/jsonalchemy/blob/e7b5cae7a9a48f9ba62758a3586b935c6b11f790/tests/test_readers.py.

We might expand this feature to add support for JSONPath, which is essentially the analogue of XPath for JSON data. JSONPath supports additional syntax, like querying for all `bar`s inside a `foo` array (`'foo[*].bar'`), or querying for a `bar` or a `baz` inside of a `foo` object (`'foo[bar, baz]'`).

One use case for this is easily defining calculated fields which combine real fields inside of the record (think the `authors`, `first_author`, `other_authors` example). There's probably more, and I'd like to know about these.

NB: JSONPath has no official RFC. There's an RFC for something called JSON Pointer, which is considerably less powerful: https://tools.ietf.org/html/rfc6901. On the other hand, there's a reasonably mature implementation: https://github.com/kennknowles/python-jsonpath-rw.

CC: @jalavik @kaplun @MSusik

**Comment by egabancho** [comment]
+1 for JSONPath

The current implementation leads, sometimes, to an ambiguous situations, for example in `foo['bar.0.baz']` is imposible to know if the `0` is a key inside a dictionary or the position in a list.
I think the [dictdiffer](http://dictdiffer.readthedocs.org/en/latest/#dictdiffer.dot_lookup) suffers the same issue. (cc @jirikuncar)

**Comment by MSusik** [comment]
+1 for JSONPath.

Not a standard, but it is widely used, and the solutions should be almost ready, the only thing needed is probably integration.

**Comment by lnielsen** [comment]
Sounds like a good idea to me. :+1:

**Comment by jacquerie** [comment]
Implementing JSONPath was very easy: https://github.com/jacquerie/jsonalchemy/commit/5238aaea547aee1aca270231a9058808c18b0e37.

`JSONBase` now has a method `search` with accepts a JSONPath query. It returns a `JSONArray` containing the results, which can then be queried again (not shown in the tests).

**Comment by jirikuncar** [comment]
@jacquerie I like the JSONPath implementation. But why JSON Pointer is not enough especially when it can be nicely combined with JSON Patch (https://tools.ietf.org/html/rfc6902)?

**Comment by jacquerie** [comment]
The problem of JSON Pointer is that you can only point a single element. So, for instance, you cannot write a query that returns all authors of a document, while with JSONPath you can.

**Comment by jirikuncar** [comment]
We might want to support both or even more (see also http://jsonauts.github.io/#query) as they might have different use cases.

**Comment by jirikuncar** [comment]
Both JSON Path and JSON Pointer can be used via their APIs without tight integration with JSONAlchemy.
