### ISSUE TITLE
RFC: templates

### ISSUE THREAD

**Issue by jacquerie** [inveniosoftware/jsonalchemy#40]
[jdorn/json-editor](https://github.com/jdorn/json-editor) supports a nice syntax for having fields defined in terms of other fields: https://github.com/jdorn/json-editor#templates.

Given the following schema

``` JSON
{
    "type": "object",
    "properties": {
        "first_name": { "type": "string" },
        "last_name": { "type": "string" }
    }
}
```

one can define a derived field `full_name` as such:

``` JSON
{
  ...

  "properties": {
    ...

    "full_name": {
      "type": "string",
      "template": "{{fname}} {{lname}}",
      "watch": {
        "fname": "first_name",
        "lname": "last_name"
      }
    }
  }
}
```

where the `watch` property specifies the bindings between names and properties, identified by the absolute path from the root.

In the case of [jdorn/json-editor](https://github.com/jdorn/json-editor), the `template` property can use one of several JavaScript templating engines. In our case, @kaplun suggests to use Jinja2 for consistency and caching.

NB: There's some overlapping with the JSONPath RFC (#39).
CC: @MSusik @lnielsen

**Comment by jmartinm** [comment]
> In the case of jdorn/json-editor, the template property can use one of several JavaScript templating engines. In our case, @kaplun suggests to use Jinja2 for consistency and caching.

If you go for JavaScript templating, note that we are using in several places already Hogan (https://github.com/inveniosoftware/invenio/blob/7dd6e062ed6f2c0f638e2c3ff6e6a44acf8c0604/invenio/base/bundles.py#L118)

**Comment by lnielsen** [comment]
Thanks for choosing full name since it can expose a lot of troubles :-) Most importantly `full_name != first name + ' ' + last name` (see http://www.w3.org/International/questions/qa-personal-names)

The short version is you should just store `full_name`. Anyway, if you want to split the name, then you'll need a third property a la `name_order` which decide the order of how you concatenate the name. So to get back to the template you'll need an if/else-clause in the template based on the value of the `name_order` property.

**Comment by lnielsen** [comment]
Regarding the template syntax then I think it depends on where it needs to be used, but Mustache templates (which Hogan uses) I also think is a good start. Mustache templates are more simpler and more restrictive than Jinja templates which in this connection could be beneficial (also they can be easily rendered in nearly any language, Jinja on the other hand cannot).

**Comment by kaplun** [comment]
On the other hand would be good to find a common ground: templates are going to be used to implement derived fields, and in an ideal world the template should be parsed in the same way on the client (i.e. json-editor which supports whatever) and on the server (where we use Jinja2). So IMHO to find a common syntax would be great.

**Comment by lnielsen** [comment]
Mustache client-side: Hogan
Mustache server-side: https://github.com/defunkt/pystache 
Jinja2 server-side: http://jinja.pocoo.org/docs/dev/
Jinja2 client-side: https://github.com/syrusakbary/jsjinja

Problem with Jinja2 for this particular case is that you can do too many things such as:

```
{{ var|myfilter }}
{% mytag %}
```

That means you need to implement the tags in both JS/Python and ensure they are in sync, not to mention Jinja has lot of extensions. All in all, I'm afraid that what you render server-side is not the same as what you render client-side.

Mustache resembles Jinja2, but is restricted and the syntax is very easy to learn (plus we are already using them other places in Invenio).

**Comment by MSusik** [comment]
Currently the implementation uses `jinja` on the server-side https://github.com/MSusik/jsonalchemy/commit/2b39cae0f1487b2a1d68ccf47f6e7ca3b33fa665
, but it is trivial to switch to another syntax. We will probably switch to `pystache` if there will be too many problems on JS side.

**Comment by jirikuncar** [comment]
Templating should happen on client site or via serializers used in REST APIs.
